name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: sudo apt-get install -y cmake g++
    - name: checkout dir
      run: mkdir build
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
    - name: Run Tests
      run: ctest --test-dir build --output-on-failure